import type { Product } from "@/lib/types";

export const CATALOG_VERSION = "demo-2026-09";

export const products: Product[] = [
  {
    id: "sugary-cereal",
    name: "Sugary cereal",
    category: "breakfast",
    price: 5,
    currency: "USD",
    nutritionScore: 2,
    tags: ["vegetarian"],
    prepMinutes: 2,
    cuisineTags: ["global"],
    allergens: ["gluten"],
    healthierSwapIds: ["rolled-oats"],
    packSizeLabel: "300 g box",
    catalogVersion: CATALOG_VERSION
  },
  {
    id: "rolled-oats",
    name: "Rolled oats",
    category: "breakfast",
    price: 2.5,
    currency: "USD",
    nutritionScore: 9,
    tags: ["vegetarian", "vegan", "high-fibre", "quick"],
    prepMinutes: 5,
    cuisineTags: ["Indian-friendly", "global"],
    allergens: ["gluten"],
    healthierSwapIds: [],
    packSizeLabel: "500 g bag",
    catalogVersion: CATALOG_VERSION
  },
  {
    id: "instant-noodles",
    name: "Instant noodles",
    category: "staple",
    price: 1.5,
    currency: "USD",
    nutritionScore: 3,
    tags: ["vegetarian", "quick"],
    prepMinutes: 5,
    cuisineTags: ["Asian-friendly", "global"],
    allergens: ["gluten"],
    healthierSwapIds: ["whole-wheat-pasta"],
    packSizeLabel: "70 g pack",
    catalogVersion: CATALOG_VERSION
  },
  {
    id: "whole-wheat-pasta",
    name: "Whole-wheat pasta",
    category: "staple",
    price: 1.4,
    currency: "USD",
    nutritionScore: 8,
    tags: ["vegetarian", "vegan", "high-fibre"],
    prepMinutes: 12,
    cuisineTags: ["Italian-friendly", "global"],
    allergens: ["gluten"],
    healthierSwapIds: [],
    packSizeLabel: "500 g pack",
    catalogVersion: CATALOG_VERSION
  },
  {
    id: "soda",
    name: "Soda",
    category: "drink",
    price: 3,
    currency: "USD",
    nutritionScore: 1,
    tags: ["vegan", "ready-to-drink"],
    prepMinutes: 0,
    cuisineTags: ["global"],
    allergens: [],
    healthierSwapIds: ["sparkling-water"],
    packSizeLabel: "2 L bottle",
    catalogVersion: CATALOG_VERSION
  },
  {
    id: "sparkling-water",
    name: "Sparkling water",
    category: "drink",
    price: 2,
    currency: "USD",
    nutritionScore: 9,
    tags: ["vegan", "ready-to-drink", "no-added-sugar"],
    prepMinutes: 0,
    cuisineTags: ["global"],
    allergens: [],
    healthierSwapIds: [],
    packSizeLabel: "2 L bottle",
    catalogVersion: CATALOG_VERSION
  },
  {
    id: "potato-chips",
    name: "Potato chips",
    category: "snack",
    price: 4,
    currency: "USD",
    nutritionScore: 2,
    tags: ["vegetarian", "ready-to-eat"],
    prepMinutes: 0,
    cuisineTags: ["global"],
    allergens: [],
    healthierSwapIds: ["roasted-chickpeas"],
    packSizeLabel: "200 g bag",
    catalogVersion: CATALOG_VERSION
  },
  {
    id: "roasted-chickpeas",
    name: "Roasted chickpeas",
    category: "snack",
    price: 3.75,
    currency: "USD",
    nutritionScore: 8,
    tags: ["vegetarian", "vegan", "high-fibre", "protein", "ready-to-eat"],
    prepMinutes: 0,
    cuisineTags: ["Indian-friendly", "global"],
    allergens: [],
    healthierSwapIds: [],
    packSizeLabel: "150 g bag",
    catalogVersion: CATALOG_VERSION
  },
  {
    id: "white-bread",
    name: "White bread",
    category: "bread",
    price: 2.8,
    currency: "USD",
    nutritionScore: 3,
    tags: ["vegetarian"],
    prepMinutes: 0,
    cuisineTags: ["global"],
    allergens: ["gluten"],
    healthierSwapIds: ["wholegrain-bread"],
    packSizeLabel: "600 g loaf",
    catalogVersion: CATALOG_VERSION
  },
  {
    id: "wholegrain-bread",
    name: "Wholegrain bread",
    category: "bread",
    price: 2.75,
    currency: "USD",
    nutritionScore: 8,
    tags: ["vegetarian", "high-fibre"],
    prepMinutes: 0,
    cuisineTags: ["global"],
    allergens: ["gluten"],
    healthierSwapIds: [],
    packSizeLabel: "600 g loaf",
    catalogVersion: CATALOG_VERSION
  },
  {
    id: "frozen-pizza",
    name: "Frozen cheese pizza",
    category: "frozen",
    price: 6,
    currency: "USD",
    nutritionScore: 3,
    tags: ["vegetarian"],
    prepMinutes: 15,
    cuisineTags: ["Italian-friendly", "global"],
    allergens: ["gluten", "milk"],
    healthierSwapIds: ["frozen-vegetable-mix"],
    packSizeLabel: "400 g pizza",
    catalogVersion: CATALOG_VERSION
  },
  {
    id: "frozen-vegetable-mix",
    name: "Frozen vegetable mix",
    category: "frozen",
    price: 4.5,
    currency: "USD",
    nutritionScore: 9,
    tags: ["vegetarian", "vegan", "quick", "high-fibre"],
    prepMinutes: 8,
    cuisineTags: ["Indian-friendly", "global"],
    allergens: [],
    healthierSwapIds: [],
    packSizeLabel: "500 g bag",
    catalogVersion: CATALOG_VERSION
  }
];

export const productsById = new Map(products.map((product) => [product.id, product]));
